[package]
version = "0.1.0"
distribution = "2201.12.6"

[build-options]
observabilityIncluded = true

[package]
version = "0.1.0"
distribution = "2201.12.6"
org = "guidance-ss5/Codenet"  
name = "codenet_backend" 

[build-options]
observabilityIncluded = true

# Add this dependency section
[dependencies]
"ballerinax/mongodb" = "1.10.0"
